---
swagger: "2.0"
info:
  version: "1.0"
  title: "docuinfo-groups"
host: "mvlebefip3.execute-api.eu-central-1.amazonaws.com"
basePath: "/Prod"
schemes:
- "https"
paths:
  /create_group:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - name
            properties:
              token:
                type: string
              name:
                type: string
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "errorCode" : 0
            }
  /delete_group:
    post:
      parameters:
        - in: body
          name: body
          schema: 
            required:
              - token
              - groupID
            properties:
              token:
                type: string
              groupID:
                type: integer
      responses:
        '200':
          description: |-
            {
            "message": "success"
            }
        '400':
          description: |-
            {
            "errorCode" : 0
            }

